services:
  - type: web
    name: django-pos-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn pos.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pos.settings
      - key: PYTHON_VERSION
        value: 3.10
